[package]
name = "crit-dev/forbidden-v2"
version = "2.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
robloxstatemachine = "prooheckcp/robloxstatemachine@1.1.7"